<?php
$labels['mh_title'] = 'Messagi in rilievo';
$labels['mh_matches'] = 'corrispondenze';
$labels['mh_color'] = 'colore';
$labels['mh_delete'] = 'elimina';
$labels['mh_delete_description'] = 'Elimina questa riga';
$labels['mh_add'] = 'aggiungi riga';
$labels['mh_add_description'] = 'Aggiungi una riga ulteriore sotto questa riga';
$labels['deleteconfirm'] = 'Sei sicuro di voler cancellare questa regola?';

// these should never happen, but add anyways
$labels['headererror'] = 'Errore nella regola del messaggio';
$labels['inputempty'] = 'Una o più corrispondenze sono vuote';
$labels['invalidcolor'] = 'Colore non valido';
