<?php
$labels['mh_title'] = 'Podświetlanie wiadomości';
$labels['mh_matches'] = 'pasuje';
$labels['mh_color'] = 'kolor';
$labels['mh_delete'] = 'usuń';
$labels['mh_delete_description'] = 'Usuń tę linię';
$labels['mh_add'] = 'dodaj rząd';
$labels['mh_add_description'] = 'Dodaje dodatkowy rząd ponieżej tego';
$labels['deleteconfirm'] = 'Czy na pewno chesz usunąć tę regułę?';

// these should never happen, but add anyways
$labels['headererror'] = 'Błąd w regule wiadomości';
$labels['inputempty'] = 'Jedno lub więcej dopasowań jest puste';
$labels['invalidcolor'] = 'Błędny kolor';

?>
